### ISSUE TITLE
What is this and why did it show up in my visual studio installed extensions list?

### ISSUE THREAD

**Issue by StingyJack** [MobileEssentials/Merq#27]
I cant tell what this may be for or used by based on the readme.

**Comment by kzu** [comment]
This is an internal architectural component used by Xamarin to provide loosely coupled communication cross the various pieces of the extension, based on the core `ICommandBus` and `IEventStream` MEF services.

This allows pieces of the Xamarin extension that are developed by different teams to have a contracts-based shared assembly, without having to sync on implementations, which can evolve independently. 

It's a generic message-based pattern that's commonly used to decouple components , and we leverage it internally.

We plan on making the extension a `SystemComponent` so it won't show up in your extension manager. FWIW, any VS extension can leverage this same mechanism by just importing the `IEventStream` and listening for events on it, for example.

I hope this helps clarify it.

**Comment by StingyJack** [comment]
Yes, @kzu, thank you. I was trying to weed out any extensions that could be causing the repeated crashes I've been having, and this one was one of many that had little public info.
